[package]
name = "folder-size-analyzer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2.3.2"
chrono = "0.4.19"
rayon = "1.5.3"
